### PR TITLE
Update AppData configuration file.

### PR DESCRIPTION
**Pull request by jpopelka**
I've been asked by Richard Hughes to update the AppData config file so I ran
`appstream-util upgrade firewall-config.appdata.xml.in`
filled the new metadata fields and here's the result.

### CODE REVIEW

**Comment by t-woerner** [comment]
Is this also working with older appstream versions?

**Comment by jpopelka** [comment]
Not sure, but I'd expect that the unknown metadata fields are ignored.

**Comment by t-woerner** [comment]
Please use https://raw.githubusercontent.com/t-woerner/firewalld/master/doc/firewall-config.png for the firewall-config screenshot.

**Comment by t-woerner** [comment]
According to https://people.freedesktop.org/~hughsient/appdata/ it should be working also with the old version.

**Comment by jpopelka** [comment]
Rebased with the new screenshot link.

**Comment by t-woerner** [comment]
The image is new with different size: 870 x 600
Is the image size needed there at all? If the image gets replaces sometime in the future for example the size might not match again.

**Comment by jpopelka** [comment]
No, I don't think it's needed. Rebased.

**Comment by t-woerner** [comment]
Thanks for the patch

**Comment by hughsie** [comment]
FWIW, the "new" metadata format is supported even in Fedora 21, so updating now is completely safe.

**Pull request merged**
